name: fitshield
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_slidable: ^0.6.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0  # Merged under dev_dependencies

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/fitlogo.svg"  # Path to your app icon

flutter:
  uses-material-design: true

  # Assets for images or icons
  assets:
    - assets/icons/full_menu.svg
    - assets/icons/healthy.svg
    - assets/icons/cart.svg
    - assets/images/fried_rice.jpg
    - assets/images/cappuccino.jpg
    - assets/images/burger1.jpg
    - assets/images/burger2.jpg
    - assets/images/burger3.jpg
    - assets/images/burger4.jpg
    - assets/images/burger5.jpg
    - assets/card_image.png
    - assets/gpay_logo.png
    - assets/mastercard_logo.png
    - assets/paypal_logo.png
    - assets/applepay_logo.png